#!/bin/bash
if [ -n "$1" ]
then
  if [ "$1" == "del" ]
  then
    docker rmi metrics-collector
  else
    docker build -t metrics-collector .
    docker run -ti --rm --pid host --network host metrics-collector python script.py $1
  fi
else
  echo "No parameters found. Please write cpu or mem."
fi
